# Generated by Django 5.0.1 on 2024-02-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_productenter_enterproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterproduct',
            name='entered_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
