# Generated by Django 5.0.1 on 2024-02-07 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_enterproduct_entered_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnterProduct',
        ),
    ]
