# Generated by Django 5.0.1 on 2024-02-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_enterproduct_created_at_enterproduct_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterproduct',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
