# Generated by Django 5.0.1 on 2024-02-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_enterproduct_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterproduct',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
